# Generated by Django 4.1.4 on 2026-04-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_uid', models.CharField(blank=True, default='', max_length=120)),
                ('event_count', models.IntegerField(default=0)),
                ('first_event_id', models.BigIntegerField(default=0)),
                ('last_event_id', models.BigIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('compression', models.CharField(blank=True, default='', max_length=32)),
                ('checksum', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('building', 'Building'), ('ready', 'Ready'), ('sent', 'Sent'), ('acked', 'Acknowledged'), ('failed', 'Failed')], default='building', max_length=32)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('built_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replication_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_batches', to='srdf.replicationservice')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReplicationCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('capture', 'Capture'), ('shipper', 'Shipper'), ('receiver', 'Receiver'), ('applier', 'Applier')], max_length=32)),
                ('engine', models.CharField(default='mariadb', max_length=32)),
                ('log_file', models.CharField(blank=True, default='', max_length=255)),
                ('log_pos', models.BigIntegerField(default=0)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=120)),
                ('checkpoint_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='srdf.node')),
                ('replication_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='srdf.replicationservice')),
            ],
            options={
                'ordering': ['replication_service_id', 'node_id', 'direction'],
            },
        ),
        migrations.CreateModel(
            name='OutboundChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(default='mariadb', max_length=32)),
                ('database_name', models.CharField(blank=True, default='', max_length=120)),
                ('table_name', models.CharField(blank=True, default='', max_length=120)),
                ('operation', models.CharField(blank=True, default='', max_length=32)),
                ('event_uid', models.CharField(blank=True, default='', max_length=120)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=120)),
                ('log_file', models.CharField(blank=True, default='', max_length=255)),
                ('log_pos', models.BigIntegerField(default=0)),
                ('primary_key_data', models.JSONField(blank=True, default=dict)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('event_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('batched', 'Batched'), ('sent', 'Sent'), ('acked', 'Acknowledged'), ('applied', 'Applied'), ('failed', 'Failed'), ('dead', 'Dead Letter')], default='pending', max_length=32)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('batched_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replication_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_events', to='srdf.replicationservice')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_events', to='srdf.node')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InboundChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(default='mariadb', max_length=32)),
                ('database_name', models.CharField(blank=True, default='', max_length=120)),
                ('table_name', models.CharField(blank=True, default='', max_length=120)),
                ('operation', models.CharField(blank=True, default='', max_length=32)),
                ('event_uid', models.CharField(blank=True, default='', max_length=120)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=120)),
                ('source_log_file', models.CharField(blank=True, default='', max_length=255)),
                ('source_log_pos', models.BigIntegerField(default=0)),
                ('primary_key_data', models.JSONField(blank=True, default=dict)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('event_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('applying', 'Applying'), ('applied', 'Applied'), ('failed', 'Failed'), ('dead', 'Dead Letter')], default='received', max_length=32)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('replication_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_events', to='srdf.replicationservice')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_events', to='srdf.node')),
                ('transport_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_events', to='srdf.transportbatch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
