# Generated by Django 4.1.4 on 2026-04-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0002_transportbatch_replicationcheckpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='db_port',
            field=models.IntegerField(default=3306),
        ),
    ]
