# Generated by Django 4.1.4 on 2026-04-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0003_node_db_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replicationservice',
            name='service_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mariadb', 'MariaDB'), ('filesync', 'File Sync'), ('nginx', 'Nginx/Proxy')], max_length=32),
        ),
    ]
