# Generated by Django 4.1.4 on 2026-04-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0004_alter_replicationservice_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLObjectScopeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_system_rule', models.BooleanField(default=False)),
                ('engine', models.CharField(choices=[('all', 'All'), ('mariadb', 'MariaDB'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL')], default='all', max_length=32)),
                ('policy_mode', models.CharField(choices=[('include', 'Include'), ('exclude', 'Exclude')], default='exclude', max_length=16)),
                ('object_type', models.CharField(choices=[('database', 'Database'), ('table', 'Table')], default='table', max_length=32)),
                ('match_mode', models.CharField(choices=[('exact', 'Exact'), ('prefix', 'Prefix'), ('contains', 'Contains')], default='exact', max_length=16)),
                ('database_name', models.CharField(blank=True, default='', max_length=120)),
                ('table_name', models.CharField(blank=True, default='', max_length=120)),
                ('priority', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
    ]
