# Generated by Django 4.1.4 on 2026-04-06 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0005_sqlobjectscoperule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootstrapPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_enabled', models.BooleanField(default=True)),
                ('scope_mode', models.CharField(choices=[('database', 'Whole database'), ('tables', 'Selected tables')], default='database', max_length=32)),
                ('source_database_name', models.CharField(max_length=120)),
                ('include_tables_csv', models.TextField(blank=True, default='')),
                ('exclude_tables_csv', models.TextField(blank=True, default='')),
                ('like_filter', models.CharField(blank=True, default='', max_length=120)),
                ('recreate_table', models.BooleanField(default=False)),
                ('truncate_target', models.BooleanField(default=True)),
                ('auto_exclude_srdf', models.BooleanField(default=True)),
                ('validate_snapshot', models.BooleanField(default=False)),
                ('parallel_workers', models.IntegerField(default=1)),
                ('table_limit', models.IntegerField(default=0)),
                ('execution_order', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='draft', max_length=32)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_duration_seconds', models.FloatField(default=0)),
                ('last_total_tables', models.IntegerField(default=0)),
                ('last_success_count', models.IntegerField(default=0)),
                ('last_failed_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_result_payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replication_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootstrap_plans', to='srdf.replicationservice')),
            ],
            options={
                'ordering': ['execution_order', 'id'],
            },
        ),
    ]
