# Generated by Django 4.1.4 on 2026-04-07 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0006_bootstrapplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrapplan',
            name='bootstrap_method',
            field=models.CharField(choices=[('sql_copy', 'SQL copy'), ('mysqldump', 'mysqldump')], default='sql_copy', max_length=32),
        ),
        migrations.AddField(
            model_name='bootstrapplan',
            name='database_exclude_csv',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bootstrapplan',
            name='database_include_csv',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bootstrapplan',
            name='database_like_pattern',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='bootstrapplan',
            name='database_parallel_workers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bootstrapplan',
            name='last_total_databases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bootstrapplan',
            name='scope_mode',
            field=models.CharField(choices=[('database', 'Whole database'), ('tables', 'Selected tables'), ('pattern', 'Pattern based')], default='database', max_length=32),
        ),
        migrations.AlterField(
            model_name='bootstrapplan',
            name='source_database_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='BootstrapPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('execution_order', models.IntegerField(default=100)),
                ('source_database_name', models.CharField(max_length=120)),
                ('table_name', models.CharField(blank=True, default='', max_length=120)),
                ('recreate_table', models.BooleanField(default=False)),
                ('truncate_target', models.BooleanField(default=True)),
                ('validate_snapshot', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=32)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_duration_seconds', models.FloatField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_result_payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bootstrap_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='srdf.bootstrapplan')),
            ],
            options={
                'ordering': ['execution_order', 'id'],
            },
        ),
    ]
