# Generated by Django 4.1.4 on 2026-04-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0007_bootstrapplan_bootstrap_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootstrapPlanTableSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('execution_order', models.IntegerField(default=100)),
                ('recreate_table', models.BooleanField(default=False)),
                ('truncate_target', models.BooleanField(default=True)),
                ('validate_snapshot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bootstrap_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_selections', to='srdf.bootstrapplan')),
            ],
            options={
                'ordering': ['execution_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SourceDatabaseCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(blank=True, default='', max_length=32)),
                ('database_name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('discovered_at', models.DateTimeField(auto_now=True)),
                ('replication_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_database_catalogs', to='srdf.replicationservice')),
            ],
            options={
                'ordering': ['database_name'],
            },
        ),
        migrations.CreateModel(
            name='SourceTableCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('discovered_at', models.DateTimeField(auto_now=True)),
                ('replication_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_table_catalogs', to='srdf.replicationservice')),
                ('source_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_catalogs', to='srdf.sourcedatabasecatalog')),
            ],
            options={
                'ordering': ['source_database__database_name', 'table_name'],
            },
        ),
        migrations.DeleteModel(
            name='BootstrapPlanItem',
        ),
        migrations.AddField(
            model_name='bootstrapplantableselection',
            name='source_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootstrap_plan_selections', to='srdf.sourcetablecatalog'),
        ),
        migrations.AddField(
            model_name='bootstrapplan',
            name='selected_tables',
            field=models.ManyToManyField(blank=True, related_name='bootstrap_plans', through='srdf.BootstrapPlanTableSelection', to='srdf.sourcetablecatalog'),
        ),
    ]
