# Generated by Django 4.1.4 on 2026-04-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0008_bootstrapplantableselection_sourcedatabasecatalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrapplantableselection',
            name='last_duration_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bootstrapplantableselection',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bootstrapplantableselection',
            name='last_result_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bootstrapplantableselection',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bootstrapplantableselection',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='bootstrapplantableselection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
