# Generated by Django 4.1.4 on 2026-04-07 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0009_bootstrapplantableselection_last_duration_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootstrapPlanExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_by', models.CharField(blank=True, default='', max_length=120)),
                ('trigger_mode', models.CharField(blank=True, default='manual', max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=32)),
                ('dry_run', models.BooleanField(default=False)),
                ('total_databases', models.IntegerField(default=0)),
                ('total_tables', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bootstrap_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='srdf.bootstrapplan')),
                ('replication_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootstrap_plan_executions', to='srdf.replicationservice')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BootstrapPlanExecutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(blank=True, default='', max_length=120)),
                ('table_name', models.CharField(blank=True, default='', max_length=120)),
                ('bootstrap_method', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=32)),
                ('recreate_table', models.BooleanField(default=False)),
                ('truncate_target', models.BooleanField(default=False)),
                ('validate_snapshot', models.BooleanField(default=False)),
                ('dry_run', models.BooleanField(default=False)),
                ('copied_rows', models.BigIntegerField(default=0)),
                ('source_row_count', models.BigIntegerField(default=0)),
                ('target_row_count', models.BigIntegerField(default=0)),
                ('source_checksum', models.CharField(blank=True, default='', max_length=255)),
                ('target_checksum', models.CharField(blank=True, default='', max_length=255)),
                ('snapshot_ok', models.BooleanField(default=True)),
                ('table_created', models.BooleanField(default=False)),
                ('table_truncated', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bootstrap_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='srdf.bootstrapplanexecution')),
                ('bootstrap_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_items', to='srdf.bootstrapplan')),
                ('plan_table_selection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_items', to='srdf.bootstrapplantableselection')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
