# Generated by Django 4.1.4 on 2026-04-07 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0010_bootstrapplanexecution_bootstrapplanexecutionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrapplanexecution',
            name='parent_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replays', to='srdf.bootstrapplanexecution'),
        ),
        migrations.AddField(
            model_name='bootstrapplanexecution',
            name='replay_mode',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='bootstrapplanexecution',
            name='retry_failed_only',
            field=models.BooleanField(default=False),
        ),
    ]
