# Generated by Django 4.1.4 on 2026-04-08 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0011_bootstrapplanexecution_parent_execution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRDFOrchestratorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uid', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial'), ('stopped', 'Stopped')], default='running', max_length=32)),
                ('trigger_mode', models.CharField(choices=[('daemon', 'Daemon'), ('manual', 'Manual'), ('resume', 'Resume'), ('recovery', 'Recovery')], default='daemon', max_length=32)),
                ('sleep_seconds', models.IntegerField(default=10)),
                ('service_filter_csv', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('total_services', models.IntegerField(default=0)),
                ('success_services', models.IntegerField(default=0)),
                ('failed_services', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SRDFServiceRuntimeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('stop_requested', models.BooleanField(default=False)),
                ('current_phase', models.CharField(choices=[('idle', 'Idle'), ('capture', 'Capture'), ('deduplicate', 'Deduplicate'), ('compress', 'Compress'), ('encrypt', 'Encrypt'), ('batch_build', 'Batch Build'), ('ship', 'Ship'), ('wait_ack', 'Wait Ack'), ('receive', 'Receive'), ('apply', 'Apply'), ('checkpoint', 'Checkpoint'), ('bootstrap', 'Bootstrap'), ('paused', 'Paused'), ('error', 'Error')], default='idle', max_length=32)),
                ('last_success_phase', models.CharField(blank=True, default='', max_length=32)),
                ('next_phase', models.CharField(blank=True, default='', max_length=32)),
                ('cycle_number', models.BigIntegerField(default=0)),
                ('consecutive_error_count', models.IntegerField(default=0)),
                ('last_return_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('capture_checkpoint', models.JSONField(blank=True, default=dict)),
                ('transport_checkpoint', models.JSONField(blank=True, default=dict)),
                ('apply_checkpoint', models.JSONField(blank=True, default=dict)),
                ('last_capture_at', models.DateTimeField(blank=True, null=True)),
                ('last_deduplicate_at', models.DateTimeField(blank=True, null=True)),
                ('last_compress_at', models.DateTimeField(blank=True, null=True)),
                ('last_encrypt_at', models.DateTimeField(blank=True, null=True)),
                ('last_batch_build_at', models.DateTimeField(blank=True, null=True)),
                ('last_ship_at', models.DateTimeField(blank=True, null=True)),
                ('last_wait_ack_at', models.DateTimeField(blank=True, null=True)),
                ('last_receive_at', models.DateTimeField(blank=True, null=True)),
                ('last_apply_at', models.DateTimeField(blank=True, null=True)),
                ('last_checkpoint_at', models.DateTimeField(blank=True, null=True)),
                ('last_bootstrap_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_finished_at', models.DateTimeField(blank=True, null=True)),
                ('runtime_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replication_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_state', to='srdf.replicationservice')),
            ],
            options={
                'ordering': ['replication_service_id'],
            },
        ),
        migrations.CreateModel(
            name='SRDFServicePhaseExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.BigIntegerField(default=0)),
                ('phase_name', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('retry', 'Retry'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('stopped', 'Stopped')], default='running', max_length=32)),
                ('return_code', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('processed_count', models.BigIntegerField(default=0)),
                ('success_count', models.BigIntegerField(default=0)),
                ('failed_count', models.BigIntegerField(default=0)),
                ('skipped_count', models.BigIntegerField(default=0)),
                ('retry_after_seconds', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orchestrator_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_executions', to='srdf.srdforchestratorrun')),
                ('replication_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_executions', to='srdf.replicationservice')),
                ('runtime_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_executions', to='srdf.srdfserviceruntimestate')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SRDFServiceExecutionLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('owner_token', models.CharField(blank=True, default='', max_length=120)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replication_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_locks', to='srdf.replicationservice')),
            ],
            options={
                'ordering': ['replication_service_id', 'name'],
            },
        ),
    ]
