# Generated by Django 4.1.4 on 2026-04-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0012_srdforchestratorrun_srdfserviceruntimestate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRDFSettingDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('capture', 'Capture'), ('transport', 'Transport'), ('apply', 'Apply'), ('bootstrap', 'Bootstrap'), ('orchestrator', 'Orchestrator'), ('security', 'Security'), ('performance', 'Performance'), ('other', 'Other')], default='other', max_length=32)),
                ('phase', models.CharField(choices=[('all', 'All'), ('capture', 'Capture'), ('deduplicate', 'Deduplicate'), ('compress', 'Compress'), ('encrypt', 'Encrypt'), ('batch_build', 'Batch Build'), ('ship', 'Ship'), ('wait_ack', 'Wait ACK'), ('receive', 'Receive'), ('apply', 'Apply'), ('checkpoint', 'Checkpoint'), ('bootstrap', 'Bootstrap'), ('orchestrator', 'Orchestrator')], default='all', max_length=32)),
                ('engine', models.CharField(choices=[('all', 'All'), ('mysql', 'MySQL'), ('mariadb', 'MariaDB'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('filesync', 'File Sync'), ('nginx', 'Nginx/Proxy')], default='all', max_length=32)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=32)),
                ('default_value', models.TextField(blank=True, default='')),
                ('default_value_json', models.JSONField(blank=True, default=dict)),
                ('is_required', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'phase', 'engine', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SRDFSettingValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('engine', 'Engine'), ('company', 'Company'), ('client', 'Client'), ('service', 'Replication Service'), ('node', 'Node')], default='global', max_length=32)),
                ('engine', models.CharField(choices=[('all', 'All'), ('mysql', 'MySQL'), ('mariadb', 'MariaDB'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('filesync', 'File Sync'), ('nginx', 'Nginx/Proxy')], default='all', max_length=32)),
                ('company_name', models.CharField(blank=True, default='', max_length=150)),
                ('client_name', models.CharField(blank=True, default='', max_length=150)),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(default=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_values', to='srdf.node')),
                ('replication_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_values', to='srdf.replicationservice')),
                ('setting_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='srdf.srdfsettingdefinition')),
            ],
            options={
                'ordering': ['setting_definition__key', 'priority', 'id'],
            },
        ),
    ]
