# Generated by Django 4.1.4 on 2026-04-09 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0013_srdfsettingdefinition_srdfsettingvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRDFCronExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_uid', models.CharField(blank=True, default='', max_length=120)),
                ('cron_name', models.CharField(blank=True, default='', max_length=150)),
                ('cron_type', models.CharField(choices=[('capture', 'Capture'), ('shipper', 'Shipper'), ('receiver', 'Receiver'), ('applier', 'Applier'), ('bootstrap', 'Bootstrap'), ('orchestrator', 'Orchestrator'), ('other', 'Other')], default='other', max_length=32)),
                ('engine', models.CharField(blank=True, default='', max_length=32)),
                ('command_line', models.TextField(blank=True, default='')),
                ('initiated_by', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('blocked', 'Blocked'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], default='running', max_length=32)),
                ('return_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('input_params', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('progress_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cron_executions', to='srdf.node')),
                ('replication_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cron_executions', to='srdf.replicationservice')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
