# Generated by Django 4.1.4 on 2026-04-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0014_srdfcronexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRDFCaptureControlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uid', models.CharField(blank=True, default='', max_length=120)),
                ('control_mode', models.CharField(choices=[('list_updates', 'List updates'), ('check_updates', 'Check updates')], default='list_updates', max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='running', max_length=32)),
                ('engine', models.CharField(blank=True, default='', max_length=32)),
                ('initiated_by', models.CharField(blank=True, default='', max_length=120)),
                ('command_line', models.TextField(blank=True, default='')),
                ('checkpoint_start_file', models.CharField(blank=True, default='', max_length=255)),
                ('checkpoint_start_pos', models.BigIntegerField(default=0)),
                ('current_master_before_file', models.CharField(blank=True, default='', max_length=255)),
                ('current_master_before_pos', models.BigIntegerField(default=0)),
                ('current_master_after_file', models.CharField(blank=True, default='', max_length=255)),
                ('current_master_after_pos', models.BigIntegerField(default=0)),
                ('window_end_file', models.CharField(blank=True, default='', max_length=255)),
                ('window_end_pos', models.BigIntegerField(default=0)),
                ('total_binlog_updates', models.BigIntegerField(default=0)),
                ('total_captured_matches', models.BigIntegerField(default=0)),
                ('total_not_captured', models.BigIntegerField(default=0)),
                ('total_duplicates', models.BigIntegerField(default=0)),
                ('total_ambiguous', models.BigIntegerField(default=0)),
                ('total_ignored', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_control_runs', to='srdf.node')),
                ('replication_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_control_runs', to='srdf.replicationservice')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SRDFCaptureControlItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.BigIntegerField(default=0)),
                ('log_file', models.CharField(blank=True, default='', max_length=255)),
                ('log_pos', models.BigIntegerField(default=0)),
                ('engine', models.CharField(blank=True, default='', max_length=32)),
                ('database_name', models.CharField(blank=True, default='', max_length=120)),
                ('table_name', models.CharField(blank=True, default='', max_length=120)),
                ('operation', models.CharField(blank=True, default='', max_length=32)),
                ('row_count', models.IntegerField(default=0)),
                ('event_signature', models.CharField(blank=True, default='', max_length=255)),
                ('outbound_match_count', models.IntegerField(default=0)),
                ('first_outbound_event_id', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('not_captured', 'Not captured'), ('captured', 'Captured'), ('duplicate', 'Duplicate'), ('ambiguous', 'Ambiguous'), ('ignored', 'Ignored'), ('error', 'Error')], default='not_captured', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('payload_preview', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='srdf.srdfcapturecontrolrun')),
                ('replication_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_control_items', to='srdf.replicationservice')),
            ],
            options={
                'ordering': ['control_run_id', 'seq'],
            },
        ),
    ]
