# Generated by Django 4.1.4 on 2026-04-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0015_srdfcapturecontrolrun_srdfcapturecontrolitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='srdforchestratorrun',
            name='initiated_by',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
