# Generated by Django 4.1.4 on 2026-04-12 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0016_srdforchestratorrun_initiated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRDFDedupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uid', models.CharField(blank=True, default='', max_length=120)),
                ('initiated_by', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('warning', 'Warning'), ('failed', 'Failed')], default='running', max_length=32)),
                ('processed_count', models.IntegerField(default=0)),
                ('survivor_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('exact_duplicate_count', models.IntegerField(default=0)),
                ('neutralized_count', models.IntegerField(default=0)),
                ('collapsed_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orchestrator_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedup_runs', to='srdf.srdforchestratorrun')),
                ('phase_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedup_runs', to='srdf.srdfservicephaseexecution')),
                ('replication_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dedup_runs', to='srdf.replicationservice')),
                ('runtime_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedup_runs', to='srdf.srdfserviceruntimestate')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SRDFDedupDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(blank=True, default='', max_length=120)),
                ('table_name', models.CharField(blank=True, default='', max_length=120)),
                ('operation', models.CharField(blank=True, default='', max_length=32)),
                ('decision_type', models.CharField(choices=[('survivor', 'Survivor'), ('exact_duplicate', 'Exact duplicate'), ('collapsed', 'Collapsed'), ('neutralized', 'Neutralized'), ('passthrough', 'Passthrough')], default='passthrough', max_length=32)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('event_id', models.BigIntegerField(default=0)),
                ('survivor_event_id', models.BigIntegerField(default=0)),
                ('log_file', models.CharField(blank=True, default='', max_length=255)),
                ('log_pos', models.BigIntegerField(default=0)),
                ('group_key', models.TextField(blank=True, default='')),
                ('business_signature', models.CharField(blank=True, default='', max_length=255)),
                ('primary_key_data', models.JSONField(blank=True, default=dict)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('payload_preview', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dedup_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='srdf.srdfdeduprun')),
                ('replication_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dedup_decisions', to='srdf.replicationservice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
