# Generated by Django 4.1.4 on 2026-04-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0018_outboundchangeevent_ddl_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundchangeevent',
            name='ddl_action',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('create', 'Create'), ('alter', 'Alter'), ('drop', 'Drop')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='inboundchangeevent',
            name='event_family',
            field=models.CharField(choices=[('dml', 'DML'), ('ddl', 'DDL')], default='dml', max_length=16),
        ),
        migrations.AddField(
            model_name='inboundchangeevent',
            name='object_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inboundchangeevent',
            name='object_type',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('database', 'Database'), ('table', 'Table'), ('column', 'Column'), ('index', 'Index')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='inboundchangeevent',
            name='parent_object_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inboundchangeevent',
            name='raw_sql',
            field=models.TextField(blank=True, default=''),
        ),
    ]
