# Generated by Django 4.1.4 on 2026-04-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0019_inboundchangeevent_ddl_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRDFArchiveExecutionLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('owner_token', models.CharField(blank=True, default='', max_length=120)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SRDFArchiveRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uid', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=32)),
                ('trigger_mode', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('orchestrator', 'Orchestrator'), ('recovery', 'Recovery')], default='scheduled', max_length=32)),
                ('initiated_by', models.CharField(blank=True, default='', max_length=120)),
                ('archive_database_name', models.CharField(blank=True, default='', max_length=150)),
                ('retention_days', models.IntegerField(default=30)),
                ('batch_size', models.IntegerField(default=1000)),
                ('archive_before_datetime', models.DateTimeField(blank=True, null=True)),
                ('total_tables', models.IntegerField(default=0)),
                ('success_tables', models.IntegerField(default=0)),
                ('failed_tables', models.IntegerField(default=0)),
                ('total_rows_selected', models.BigIntegerField(default=0)),
                ('total_rows_inserted', models.BigIntegerField(default=0)),
                ('total_rows_deleted', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='srdfserviceruntimestate',
            name='current_phase',
            field=models.CharField(choices=[('idle', 'Idle'), ('capture', 'Capture'), ('deduplicate', 'Deduplicate'), ('compress', 'Compress'), ('encrypt', 'Encrypt'), ('batch_build', 'Batch Build'), ('ship', 'Ship'), ('wait_ack', 'Wait Ack'), ('receive', 'Receive'), ('apply', 'Apply'), ('checkpoint', 'Checkpoint'), ('bootstrap', 'Bootstrap'), ('archive', 'Archive'), ('paused', 'Paused'), ('error', 'Error')], default='idle', max_length=32),
        ),
        migrations.AlterField(
            model_name='srdfsettingdefinition',
            name='phase',
            field=models.CharField(choices=[('all', 'All'), ('capture', 'Capture'), ('deduplicate', 'Deduplicate'), ('compress', 'Compress'), ('encrypt', 'Encrypt'), ('batch_build', 'Batch Build'), ('ship', 'Ship'), ('wait_ack', 'Wait ACK'), ('receive', 'Receive'), ('apply', 'Apply'), ('checkpoint', 'Checkpoint'), ('bootstrap', 'Bootstrap'), ('archive', 'Archive'), ('orchestrator', 'Orchestrator')], default='all', max_length=32),
        ),
        migrations.CreateModel(
            name='SRDFArchiveRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=150)),
                ('archive_model_label', models.CharField(blank=True, default='', max_length=150)),
                ('archive_before_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=32)),
                ('selected_count', models.BigIntegerField(default=0)),
                ('inserted_count', models.BigIntegerField(default=0)),
                ('deleted_count', models.BigIntegerField(default=0)),
                ('skipped_count', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archive_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='srdf.srdfarchiverun')),
                ('replication_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_items', to='srdf.replicationservice')),
            ],
            options={
                'ordering': ['archive_run_id', 'id'],
            },
        ),
    ]
