# Generated by Django 4.1.4 on 2026-04-15 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srdf', '0020_srdfarchiveexecutionlock_srdfarchiverun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRDFInstallProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_enabled', models.BooleanField(default=True)),
                ('install_scope', models.CharField(choices=[('remote_control', 'Remote control plane only'), ('full_remote', 'Full remote install')], default='remote_control', max_length=32)),
                ('db_host', models.CharField(default='127.0.0.1', max_length=255)),
                ('db_port', models.IntegerField(default=3307)),
                ('db_user', models.CharField(default='root', max_length=120)),
                ('db_password', models.CharField(blank=True, default='', max_length=255)),
                ('control_db_name', models.CharField(default='srdf_remote_control', max_length=150)),
                ('archive_db_name', models.CharField(default='srdf_remote_archive', max_length=150)),
                ('target_db_name', models.CharField(default='target_db', max_length=150)),
                ('source_node_name', models.CharField(default='mysql-source', max_length=120)),
                ('source_hostname', models.CharField(default='localhost', max_length=255)),
                ('source_db_port', models.IntegerField(default=3306)),
                ('source_site', models.CharField(blank=True, default='site-a', max_length=120)),
                ('source_api_base_url', models.CharField(blank=True, default='', max_length=255)),
                ('target_node_name', models.CharField(default='mariadb-target', max_length=120)),
                ('target_hostname', models.CharField(default='localhost', max_length=255)),
                ('target_db_port', models.IntegerField(default=3307)),
                ('target_site', models.CharField(blank=True, default='site-b', max_length=120)),
                ('target_api_base_url', models.CharField(blank=True, default='', max_length=255)),
                ('api_token', models.CharField(blank=True, default='', max_length=255)),
                ('service_name', models.CharField(default='Mariadb-replica', max_length=150)),
                ('service_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mariadb', 'MariaDB'), ('filesync', 'File Sync'), ('nginx', 'Nginx/Proxy')], default='mariadb', max_length=32)),
                ('mode', models.CharField(choices=[('sync', 'Synchronous'), ('async', 'Asynchronous'), ('manual', 'Manual')], default='async', max_length=16)),
                ('source_db_name', models.CharField(default='oxygen_db6', max_length=150)),
                ('source_db_user', models.CharField(default='root', max_length=120)),
                ('source_db_password', models.CharField(blank=True, default='', max_length=255)),
                ('binlog_server_id', models.IntegerField(default=900001)),
                ('run_migrate', models.BooleanField(default=True)),
                ('seed_settings', models.BooleanField(default=True)),
                ('create_archive_db', models.BooleanField(default=True)),
                ('auto_create_target_db', models.BooleanField(default=True)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_result_payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SRDFInstallRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uid', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=32)),
                ('initiated_by', models.CharField(blank=True, default='', max_length=120)),
                ('control_db_name', models.CharField(blank=True, default='', max_length=150)),
                ('archive_db_name', models.CharField(blank=True, default='', max_length=150)),
                ('target_db_name', models.CharField(blank=True, default='', max_length=150)),
                ('source_node_id_value', models.BigIntegerField(default=0)),
                ('target_node_id_value', models.BigIntegerField(default=0)),
                ('replication_service_id_value', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('install_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='install_runs', to='srdf.srdfinstallprofile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
