# Generated by Django 4.1.4 on 2026-03-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafeMigrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('app_label', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('migration_target', models.CharField(blank=True, default='', max_length=180)),
                ('database_alias', models.CharField(blank=True, db_index=True, default='default', max_length=60)),
                ('status', models.CharField(blank=True, choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('failed_then_rollbacked', 'Failed then rollbacked'), ('rollback_failed', 'Rollback failed')], db_index=True, default='running', max_length=32)),
                ('rollback_on_error', models.BooleanField(default=False)),
                ('ddl_verbose', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('migrations_applied_count', models.PositiveIntegerField(default=0)),
                ('migrations_rollbacked_count', models.PositiveIntegerField(default=0)),
                ('ddl_executed_count', models.PositiveIntegerField(default=0)),
                ('ddl_failed_count', models.PositiveIntegerField(default=0)),
                ('failed_error', models.TextField(blank=True, default='')),
                ('rollback_error', models.TextField(blank=True, default='')),
                ('applied_migrations_text', models.TextField(blank=True, default='')),
                ('rollbacked_migrations_text', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafeMigrationDDL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.PositiveIntegerField(db_index=True, default=0)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('sql_kind', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('sql_text', models.TextField(blank=True, default='')),
                ('params_text', models.TextField(blank=True, default='')),
                ('error_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ddl_entries', to='migrate2026.safemigrationrun')),
            ],
            options={
                'ordering': ['seq_no'],
            },
        ),
    ]
