from srdf.models import SRDFSettingDefinition

definitions = [
    {
        "key": "archive_enabled",
        "label": "Archive enabled",
        "description": "Enable SRDF archive engine",
        "category": "orchestrator",
        "phase": "archive",
        "engine": "all",
        "value_type": "boolean",
        "default_value": "false",
        "is_required": True,
        "sort_order": 100,
    },
    {
        "key": "archive_interval_hours",
        "label": "Archive interval hours",
        "description": "Minimum interval between archive runs",
        "category": "orchestrator",
        "phase": "archive",
        "engine": "all",
        "value_type": "integer",
        "default_value": "24",
        "is_required": True,
        "sort_order": 110,
    },
    {
        "key": "archive_retention_days",
        "label": "Archive retention days",
        "description": "Archive rows older than this number of days",
        "category": "orchestrator",
        "phase": "archive",
        "engine": "all",
        "value_type": "integer",
        "default_value": "30",
        "is_required": True,
        "sort_order": 120,
    },
    {
        "key": "archive_database_name",
        "label": "Archive database alias",
        "description": "Django database alias used for archive writes",
        "category": "orchestrator",
        "phase": "archive",
        "engine": "all",
        "value_type": "string",
        "default_value": "srdf_archive",
        "is_required": True,
        "sort_order": 130,
    },
    {
        "key": "archive_batch_size",
        "label": "Archive batch size",
        "description": "Insert batch size for archive writes",
        "category": "orchestrator",
        "phase": "archive",
        "engine": "all",
        "value_type": "integer",
        "default_value": "1000",
        "is_required": True,
        "sort_order": 140,
    },
    {
        "key": "archive_pause_services_during_run",
        "label": "Pause services during archive",
        "description": "Pause orchestrator managed services during archive execution",
        "category": "orchestrator",
        "phase": "archive",
        "engine": "all",
        "value_type": "boolean",
        "default_value": "true",
        "is_required": True,
        "sort_order": 150,
    },
    {
        "key": "archive_delete_after_copy",
        "label": "Delete after copy",
        "description": "Delete source rows after successful archive copy",
        "category": "orchestrator",
        "phase": "archive",
        "engine": "all",
        "value_type": "boolean",
        "default_value": "true",
        "is_required": True,
        "sort_order": 160,
    },
    {
        "key": "archive_only_finalized_records",
        "label": "Archive only finalized records",
        "description": "Archive only finalized technical records when applicable",
        "category": "orchestrator",
        "phase": "archive",
        "engine": "all",
        "value_type": "boolean",
        "default_value": "true",
        "is_required": True,
        "sort_order": 170,
    },
    {
        "key": "archive_max_tables_per_run",
        "label": "Archive max tables per run",
        "description": "Maximum number of tables handled during one archive run",
        "category": "orchestrator",
        "phase": "archive",
        "engine": "all",
        "value_type": "integer",
        "default_value": "100",
        "is_required": True,
        "sort_order": 180,
    },
    {
        "key": "archive_max_rows_per_table_per_run",
        "label": "Archive max rows per table per run",
        "description": "Maximum rows archived per table during one run",
        "category": "orchestrator",
        "phase": "archive",
        "engine": "all",
        "value_type": "integer",
        "default_value": "5000",
        "is_required": True,
        "sort_order": 190,
    },
]

for data in definitions:
    key = data["key"]
    obj, created = SRDFSettingDefinition.objects.update_or_create(
        key=key,
        defaults=data,
    )
    print(key, "created" if created else "updated")